Fix seek callback's use of offset parameter
This was discovered by the seek_cb_test which was failing on certain
architectures (e.g., armhf):

FAIL: test_seek_function (tests.seek_cb_test.SeekCbTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/seek_cb_test.py", line 77, in test_seek_function
    self.assertEqual('1234567890.1234567890', content)
AssertionError: '1234567890.1234567890' != '12345678901234567890.1234567890'
- 1234567890.1234567890
+ 12345678901234567890.1234567890
? ++++++++++