Use urlparse.urljoin instead of os.path.join
Using a base_url like "http://www.google.de" and calling
get("/") on a curl.Curl-instance does not work.

os.path.join("http://www.google.de", "/") does not yield
the expected "http://www.google.de/" but "/" which leads to:

error: (3, '<url> malformed')

Using urljoin fixes this.

https://github.com/christophwarner/PyCurl/pull/2